import React, { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { useStore } from '../../store/useStore';
import { apiClient } from '../../utils/apiClient';
import { User, Mail, Shield, MapPin, Phone, Building, Calendar, Award, ChevronLeft, Radio, Zap } from 'lucide-react';
import TerminalStatus from './components/TerminalStatus';

// Static palette so Tailwind sees the complete class literals (dynamic
// `bg-${color}-...` strings are never generated by the build).
const FIELD_COLORS = {
    amber:   { text: 'text-amber-400',   bg: 'bg-amber-500/10',   border: 'border-amber-500/20' },
    blue:    { text: 'text-blue-400',    bg: 'bg-blue-500/10',    border: 'border-blue-500/20' },
    emerald: { text: 'text-emerald-400', bg: 'bg-emerald-500/10', border: 'border-emerald-500/20' },
    rose:    { text: 'text-rose-400',    bg: 'bg-rose-500/10',    border: 'border-rose-500/20' },
    purple:  { text: 'text-purple-400',  bg: 'bg-purple-500/10',  border: 'border-purple-500/20' },
};

function ProfileField({ icon, label, value, color = "amber" }) {
    const palette = FIELD_COLORS[color] || FIELD_COLORS.amber;
    const iconNode = icon
        ? React.createElement(icon, { className: `w-6 h-6 ${palette.text}` })
        : null;

    return (
        <div className="flex items-center gap-4 p-4 rounded-2xl bg-white/5 border border-white/10 hover:border-white/20 transition-all group">
            <div className={`w-12 h-12 rounded-xl ${palette.bg} flex items-center justify-center border ${palette.border} group-hover:scale-110 transition-transform`}>
                {iconNode}
            </div>
            <div className="flex flex-col min-w-0">
                <span className="text-[10px] font-bold text-slate-500 uppercase tracking-[0.2em]">{label}</span>
                <span className="text-sm font-bold text-slate-200 truncate">{value || 'Not provided'}</span>
            </div>
        </div>
    );
}

function formatMemberSince(value) {
    if (!value) return null;
    const d = new Date(value);
    if (Number.isNaN(d.getTime())) return null;
    return d.toLocaleDateString(undefined, { year: 'numeric', month: 'short' });
}

export default function WarehouseProfile() {
    const user = useStore((state) => state.warehouseUser);
    const warehouseToken = useStore((state) => state.warehouseToken);
    const setWarehouseUser = useStore((state) => state.setWarehouseUser);
    const navigate = useNavigate();

    const [updatingTerminal, setUpdatingTerminal] = useState(false);
    const [actionError, setActionError] = useState('');

    // --- Terminal controls (relocated from the dashboard, business logic unchanged) ---
    const handleUpdateOperationsStatus = async (newStatus) => {
        if (!warehouseToken) return;

        if (newStatus === 'open') {
            setUpdatingTerminal(true);
            setActionError('');
            try {
                const position = await new Promise((resolve, reject) => {
                    if (!navigator.geolocation) {
                        reject(new Error('Geolocation is not supported by your browser.'));
                    }
                    navigator.geolocation.getCurrentPosition(
                        (pos) => resolve(pos),
                        (err) => {
                            let msg = 'Location access is REQUIRED to open the terminal.';
                            if (err.code === 1) msg = 'PERMISSION DENIED: Please enable location services in your browser settings to open the store.';
                            else if (err.code === 2) msg = 'POSITION UNAVAILABLE: System could not verify your location.';
                            else if (err.code === 3) msg = 'TIMEOUT: Location verification timed out.';
                            reject(new Error(msg));
                        },
                        { enableHighAccuracy: true, timeout: 10000, maximumAge: 0 }
                    );
                });
                console.log('Location verified for opening:', position.coords.latitude, position.coords.longitude);
            } catch (err) {
                console.error('Location check failed:', err);
                setActionError(err.message);
                setUpdatingTerminal(false);
                return; // Stop here if location check fails
            }
        }

        setUpdatingTerminal(true);
        setActionError('');
        try {
            await apiClient.patch('/warehouse/settings', { operations_status: newStatus });
            const updatedUser = { ...user, operations_status: newStatus };
            setWarehouseUser(updatedUser, warehouseToken);
        } catch (err) {
            console.error('Failed to update terminal status:', err);
            setActionError(err.message);
        } finally {
            setUpdatingTerminal(false);
        }
    };

    const handleToggleQuickMode = async (enabled) => {
        if (!warehouseToken) return;

        setUpdatingTerminal(true);
        setActionError('');
        try {
            await apiClient.patch('/warehouse/settings', { quick_mode_enabled: enabled ? 1 : 0 });
            const updatedUser = { ...user, quick_mode_enabled: enabled ? 1 : 0 };
            setWarehouseUser(updatedUser, warehouseToken);
        } catch (err) {
            console.error('Failed to update quick mode status:', err);
            setActionError(err.message);
        } finally {
            setUpdatingTerminal(false);
        }
    };

    const profileKycStatus = (user?.profile_kyc_status || 'verified').toLowerCase();
    const isProfilePending = profileKycStatus === 'pending';
    const isOpen = (user?.operations_status || 'open') === 'open';
    const memberSince = formatMemberSince(user?.created_at);
    const warehouseType = (user?.warehouse_type || 'Micro Fulfillment').replace(/_/g, ' ');

    return (
        <div className="space-y-6 lg:space-y-8 animate-in fade-in slide-in-from-bottom-4 duration-700">
            {/* Navigation Header */}
            <div className="flex items-center justify-between gap-4 pt-[var(--app-header-height)] lg:pt-0">
                <button
                    onClick={() => navigate(-1)}
                    className="p-3 rounded-2xl bg-white/5 border border-white/10 text-slate-400 hover:text-white hover:bg-white/10 transition-all flex items-center gap-2 group"
                >
                    <ChevronLeft className="w-5 h-5 group-hover:-translate-x-1 transition-transform" />
                    <span className="text-sm font-bold pr-2">Back</span>
                </button>
                <p className="wh-ui-label text-slate-400/80">Partner Profile</p>
            </div>

            {/* Header Hero */}
            <div className="relative overflow-hidden rounded-[2rem] sm:rounded-[2.5rem] bg-gradient-to-br from-[#1e293b] to-[#0f172a] border border-white/5 p-6 sm:p-8 lg:p-12">
                <div className="absolute top-0 right-0 w-96 h-96 bg-amber-500/10 blur-[100px] -mr-48 -mt-48 rounded-full" />
                <div className="absolute bottom-0 left-0 w-64 h-64 bg-blue-500/5 blur-[80px] -ml-32 -mb-32 rounded-full" />

                <div className="relative flex flex-col md:flex-row items-center gap-6 sm:gap-8">
                    <div className="relative group">
                        <div className="absolute -inset-1 bg-gradient-to-tr from-amber-500 to-orange-500 rounded-3xl blur opacity-25 group-hover:opacity-50 transition duration-1000 group-hover:duration-200" />
                        <div className="relative w-24 h-24 sm:w-32 sm:h-32 md:w-40 md:h-40 bg-[#0f172a] border-2 border-white/10 rounded-3xl flex items-center justify-center text-4xl sm:text-5xl md:text-6xl font-black text-amber-500 shadow-2xl">
                            {user?.owner_name?.charAt(0) || 'W'}
                        </div>
                        <div className={`absolute -bottom-2 -right-2 w-9 h-9 sm:w-10 sm:h-10 border-4 border-[#0f172a] rounded-full flex items-center justify-center shadow-lg ${isProfilePending ? 'bg-amber-500' : 'bg-green-500'}`}>
                            <Shield className="w-4 h-4 text-white" />
                        </div>
                    </div>

                    <div className="flex-1 text-center md:text-left space-y-4">
                        <div className="space-y-1">
                            <h1 className="text-2xl sm:text-3xl md:text-4xl font-black text-white tracking-tight break-words">
                                {user?.owner_name || 'Warehouse Partner'}
                            </h1>
                            <div className="flex flex-wrap items-center justify-center md:justify-start gap-2 sm:gap-3">
                                <span className="px-3 py-1 rounded-full bg-amber-500/10 border border-amber-500/20 text-amber-500 text-[10px] font-black uppercase tracking-widest capitalize">
                                    {user?.role?.replace('_', ' ') || 'Partner'}
                                </span>
                                <span className="px-3 py-1 rounded-full bg-blue-500/10 border border-blue-500/20 text-blue-400 text-[10px] font-black uppercase tracking-widest">
                                    ID: {user?.partner_id || '------'}
                                </span>
                                <span className={`px-3 py-1 rounded-full text-[10px] font-black uppercase tracking-widest ${isProfilePending ? 'bg-amber-500/10 border border-amber-400/30 text-amber-300' : 'bg-emerald-500/10 border border-emerald-400/30 text-emerald-300'}`}>
                                    {isProfilePending ? 'Profile Pending' : 'Profile Verified'}
                                </span>
                                <span className={`px-3 py-1 rounded-full text-[10px] font-black uppercase tracking-widest ${isOpen ? 'bg-emerald-500/10 border border-emerald-400/30 text-emerald-300' : 'bg-rose-500/10 border border-rose-400/30 text-rose-300'}`}>
                                    {isOpen ? 'Terminal Open' : 'Terminal Closed'}
                                </span>
                            </div>
                        </div>
                        <p className="text-slate-400 text-sm max-w-xl leading-relaxed font-medium">
                            Official warehouse partner of JDLX Logistics. Authorized to manage inventory,
                            fulfill orders, and track fulfillment metrics for your assigned dark store.
                        </p>
                    </div>
                </div>
            </div>

            <div className="grid grid-cols-1 lg:grid-cols-3 gap-6 lg:gap-8">
                {/* Left column — Terminal + identity + details */}
                <div className="lg:col-span-2 space-y-6">
                    {/* Terminal Status (controls moved here from the dashboard) */}
                    <section className="space-y-3">
                        <div className="flex items-center gap-2">
                            <Zap className="w-4 h-4 text-amber-400" />
                            <h2 className="wh-ui-label text-slate-400">Terminal Control</h2>
                        </div>
                        <TerminalStatus
                            operationsStatus={user?.operations_status || 'open'}
                            weatherStatus={user?.weather_status || 'clear'}
                            pincode={user?.pincode}
                            onToggleStatus={handleUpdateOperationsStatus}
                            updatingStatus={updatingTerminal}
                            quickModeEnabled={!!user?.quick_mode_enabled}
                            onToggleQuickMode={handleToggleQuickMode}
                            compact
                        />
                        {actionError ? (
                            <div className="rounded-[20px] border border-rose-500/20 bg-rose-500/10 px-5 py-4 text-sm leading-6 text-rose-200">
                                {actionError}
                            </div>
                        ) : null}
                    </section>

                    {/* Partner Details */}
                    <div className="bg-white/5 border border-white/5 rounded-[2rem] p-6 sm:p-8 space-y-6 backdrop-blur-sm">
                        <div className="flex items-center gap-3 border-b border-white/5 pb-4">
                            <User className="w-5 h-5 text-amber-500" />
                            <h2 className="text-lg font-black text-white tracking-tight uppercase tracking-[0.1em]">Partner Details</h2>
                        </div>

                        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                            <ProfileField icon={User} label="Full Name" value={user?.owner_name} />
                            <ProfileField icon={Mail} label="Email Address" value={user?.email} color="blue" />
                            <ProfileField icon={Phone} label="Contact Number" value={user?.phone} color="emerald" />
                            <ProfileField icon={MapPin} label="Active Zone" value={user?.pincode} color="rose" />
                        </div>
                    </div>

                    {/* Warehouse Status (real data) */}
                    <div className="bg-white/5 border border-white/5 rounded-[2rem] p-6 sm:p-8 space-y-6 backdrop-blur-sm">
                        <div className="flex items-center gap-3 border-b border-white/5 pb-4">
                            <Building className="w-5 h-5 text-amber-500" />
                            <h2 className="text-lg font-black text-white tracking-tight uppercase tracking-[0.1em]">Warehouse Status</h2>
                        </div>

                        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                            <ProfileField icon={Award} label="Warehouse Type" value={warehouseType} color="amber" />
                            <ProfileField icon={Calendar} label="Member Since" value={memberSince || '—'} color="purple" />
                            <ProfileField icon={Shield} label="KYC Profile" value={isProfilePending ? 'Profile Pending' : 'Profile Verified'} color={isProfilePending ? 'amber' : 'emerald'} />
                            <ProfileField icon={Radio} label="Terminal" value={isOpen ? 'Open & Online' : 'Closed'} color={isOpen ? 'emerald' : 'rose'} />
                        </div>
                    </div>
                </div>

                {/* Right column — Operations Hub + score + security */}
                <div className="space-y-6">
                    <section className="warehouse-panel p-5 sm:p-6">
                        <p className="wh-ui-label text-slate-400/80">Operations Hub</p>
                        <div className="mt-5 space-y-3">
                            <div className="flex items-center gap-4 warehouse-subtle-card px-5 py-4">
                                <div className="flex h-10 w-10 items-center justify-center rounded-2xl border border-emerald-400/20 bg-emerald-400/10 text-emerald-300">
                                    <Radio size={18} />
                                </div>
                                <div>
                                    <p className="text-[10px] font-black uppercase tracking-widest text-slate-500 mb-0.5">Queue Status</p>
                                    <p className="text-sm font-bold text-white tracking-tight">Live feed active</p>
                                </div>
                                <span className="ml-auto h-2 w-2 rounded-full bg-emerald-400 shadow-[0_0_15px_rgba(52,211,153,0.5)] animate-pulse" />
                            </div>
                            <div className="flex items-center gap-4 warehouse-subtle-card px-5 py-4">
                                <div className="flex h-10 w-10 items-center justify-center rounded-2xl border border-blue-400/20 bg-blue-400/10 text-blue-300">
                                    <MapPin size={18} />
                                </div>
                                <div>
                                    <p className="text-[10px] font-black uppercase tracking-widest text-slate-500 mb-0.5">Active Zone</p>
                                    <p className="text-sm font-bold text-white tracking-tight">{user?.pincode || 'N/A'}</p>
                                </div>
                            </div>
                            <div className="flex items-center gap-4 warehouse-subtle-card px-5 py-4">
                                <div className="flex h-10 w-10 items-center justify-center rounded-2xl border border-amber-400/20 bg-amber-400/10 text-amber-300">
                                    <Zap size={18} />
                                </div>
                                <div>
                                    <p className="text-[10px] font-black uppercase tracking-widest text-slate-500 mb-0.5">Terminal Status</p>
                                    <p className="text-sm font-bold text-white tracking-tight">{isOpen ? 'Active and online' : 'Terminal offline'}</p>
                                </div>
                            </div>
                        </div>
                        <div className="mt-5 pt-5 border-t border-white/5 flex flex-col gap-1">
                            <p className="text-[10px] font-bold tracking-[0.16em] text-amber-500/80 uppercase">
                                Hub ID: #{user?.store_id || user?.id || '--'}
                            </p>
                            <p className="text-[10px] font-bold tracking-[0.16em] text-amber-500/80 uppercase">
                                Partner ID: {user?.partner_id || '------'}
                            </p>
                        </div>
                    </section>

                    <div className="bg-gradient-to-br from-amber-500 to-orange-600 rounded-[2rem] p-6 sm:p-8 text-slate-900 shadow-2xl shadow-amber-500/10">
                        <h3 className="text-xl font-black mb-2">Operational Score</h3>
                        <p className="text-slate-900/60 text-xs font-bold uppercase tracking-widest mb-6">Performance Rating</p>

                        <div className="flex items-end gap-2">
                            <span className="text-6xl font-black leading-none tracking-tighter">9.8</span>
                            <span className="text-xl font-bold mb-1">/10</span>
                        </div>

                        <div className="mt-8 pt-8 border-t border-slate-900/10 space-y-4">
                            <div className="flex justify-between items-center text-sm font-bold">
                                <span>Efficiency</span>
                                <span>99%</span>
                            </div>
                            <div className="w-full h-2 bg-slate-900/10 rounded-full overflow-hidden">
                                <div className="w-[99%] h-full bg-slate-900" />
                            </div>
                        </div>
                    </div>

                    <div className="bg-white/5 border border-white/5 rounded-[2rem] p-6 space-y-4">
                        <h4 className="text-[10px] font-black text-slate-500 uppercase tracking-[0.3em] px-2">Account Security</h4>
                        <button className="w-full flex items-center justify-between px-4 py-4 rounded-2xl bg-white/5 border border-white/10 text-slate-300 hover:bg-white/10 transition-all font-bold text-sm">
                            <div className="flex items-center gap-3">
                                <Shield className="w-4 h-4" />
                                <span>Two-Factor Auth</span>
                            </div>
                            <span className="text-[10px] text-emerald-500 bg-emerald-500/10 px-2 py-0.5 rounded-full uppercase tracking-widest">Active</span>
                        </button>
                    </div>
                </div>
            </div>
        </div>
    );
}
