import {
    FileText,
    ShoppingBag,
    Search,
    Filter,
    ChevronRight,
    CheckCircle2,
    XCircle,
    Clock,
    Phone,
    Package,
    Truck,
    AlertCircle,
    ArrowRight,
    Zap,
    Loader2,
    Plus,
    Check,
    X,
    Calendar,
    Edit3,
    Trash2,
    Image as ImageIcon,
    Users,
    Layers,
    Store,
    Tag,
    Home,
    MapPin,
    Navigation,
    Barcode,
    RefreshCw,
    Warehouse,
    DollarSign,
    Percent,
    Shield,
    Scale,
    Maximize,
    Thermometer,
    Info,
    Upload,
    ArrowDownCircle,
    ArrowUpCircle,
    History,
    TrendingUp,
    TrendingDown,
    Star,
    MessageSquare,
    Eye,
    ShoppingCart,
    CreditCard,
    Heart,
    Activity,
    ArrowUpRight,
    ArrowDownRight,
    Globe,
    Monitor,
    Smartphone,
    Tablet,
    AlertTriangle,
    Ban,
    IndianRupee,
    ShieldAlert,
    ChevronLeft,
    ChevronUp,
    ShieldCheck,
    Link2,
    Settings,
} from 'lucide-react'
import { API_BASE_URL, resolveMediaUrl } from '../../config'
import { useStore } from '../../store/useStore'
import VariantManager from './VariantManager'
import { apiFetch } from '../../../utils/apiFetch'
import { loadRazorpay } from '../../utils/loadRazorpay'
import { trackBeginCheckout, trackPurchase } from '../../../utils/analytics'
import { useAnalyticsContext } from '../../../context/AnalyticsContext'
import AddressPicker from '../../components/AddressPicker'
import WalletCheckout from '../../components/WalletCheckout'
import { toast } from 'react-hot-toast'