{
 "title": "JDLX Infrastructure Monitoring",
 "tags": [
  "jdlx",
  "infra"
 ],
 "refresh": "15s",
 "panels": [
  {
   "title": "Server Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(probe_success{job=\"blackbox_http\"})"
    }
   ]
  },
  {
   "title": "API Response Time (s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "avg_over_time(probe_duration_seconds{job=\"blackbox_http\"}[5m])"
    }
   ]
  },
  {
   "title": "System CPU Load (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "(sum(rate(container_cpu_usage_seconds_total{name=~\".*jdlx-backend.*\"}[2m])) / sum(machine_cpu_cores)) * 100"
    }
   ]
  },
  {
   "title": "System Memory Usage (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "(sum(container_memory_working_set_bytes{name=~\".*jdlx-backend.*\"}) / sum(machine_memory_bytes)) * 100"
    }
   ]
  },
  {
   "title": "Request Count (NGINX)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "rate(nginx_http_requests_total[1m])"
    }
   ]
  },
  {
   "title": "Error Rate (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "(1 - avg_over_time(probe_success{job=\"blackbox_http\"}[5m])) * 100"
    }
   ]
  }
 ]
}